[Icon Theme]
Name=Child
Directories=16x16/mimetypes,48x48/mimetypes,scalable/mimetypes
ScaledDirectories=64x64@2/mimetypes
Inherits=Parent,hicolor

[16x16/mimetypes]
Size=16
Type=Fixed
Context=MimeTypes

[48x48/mimetypes]
Size=48
Type=Threshold
Threshold=4
Context=MimeTypes

[scalable/mimetypes]
Size=128
MinSize=64
MaxSize=512
Type=Scalable
Context=MimeTypes

[64x64@2/mimetypes]
Size=64
Scale=2
Type=Fixed
Context=MimeTypes
