<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUserCompiledBindingsByDefault>true</AvaloniaUserCompiledBindingsByDefault>
        <AssemblyName>wlrix-toolchest</AssemblyName>
        <Version>0.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wlrix.Common\Wlrix.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Wayland" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="ReactiveUI.Avalonia" />
        <PackageReference Include="Wlrix.Avalonia" />
        <PackageReference Include="Wlrix.Avalonia.Dialogs" />
        <PackageReference Include="ZLogger" />
    </ItemGroup>

</Project>
